version: '3.4'
services:
  server:
    image: "victronenergy/venus-docker-server:latest"
    ports:
     - "8088:8088"
    volumes:
     - "config-storage:/config"
  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host
  influxdb:
    image: "influxdb:1.7"
    ports:
     - "8086:8086"
    volumes:
     - "influxdb-storage:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
  graphing:
    image: "victronenergy/venus-docker-grafana:latest"
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"
    
volumes:
 influxdb-storage:
 grafana-storage:
 config-storage:

